name: Build Node.JS

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to checkout and build to"
        required: True
        default: "14.17.5"
    
jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, windows-2022, ubuntu-20.04]
        config: [Debug, Release]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        if: runner.os == 'macOS'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'

      - name: Install nasm on Windows
        run: choco install -y nasm
        if: runner.os == 'Windows'

      - name: Install GNU patch on Windows
        run: choco install -y patch
        if: runner.os == 'Windows'

      - name: Install ninja on macOS
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
        if: runner.os == 'macOS'

      - name: Install ninja on Ubuntu
        run: sudo apt-get install -y ninja-build
        if: runner.os == 'Linux'