name: Build Node.JS

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to checkout and build to"
        required: True
        default: "14.17.5"
    
jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, windows-2019, ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        if: runner.os == 'macOS'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'

      - name: Install nasm on Windows
        run: choco install -y nasm
        if: runner.os == 'Windows'

      - name: Install GNU patch on Windows
        run: choco install -y patch
        if: runner.os == 'Windows'

      - name: Install ninja on macOS
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
        if: runner.os == 'macOS'

      - name: Install ninja on Ubuntu
        run: sudo apt-get install -y ninja-build
        if: runner.os == 'Linux'

      - name: Download node.js source code
        run: python -m nodejs.download ${{ github.event.inputs.version }}

      - name: Copy the icutrim hacky fix file
        run: |
          rm archive/tools/icu/icutrim.py
          cp nodejs/hacks/icutrim.py archive/tools/icu/icutrim.py

      - name: Build the libraries
        run: python -m nodejs.build

      - name: Archive
        run: |
          zipname=$(python -m sentry.archive)
          echo "::set-output name=zipname::$zipname"
        shell: bash
        id: archive

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.archive.outputs.zipname }}
          path: ${{ steps.archive.outputs.zipname }}
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Prepare zips
        run: |
          mkdir zips
          mv ./*/*.zip ./zips

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: sentry-${{ github.event.inputs.version }}
          release_name: sentry-${{ github.event.inputs.version }}
          
      - name: Upload release assets
        uses: csexton/release-asset-action@v2
        with:
          pattern: "zips/*.zip"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}