name: Build a new sentry libraries release with both debug / release libraries

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to checkout and build to"
        required: true
        default: "0.5.0"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, windows-2022, ubuntu-22.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        if: runner.os == 'macOS'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.22.2'

      - name: Build
        run: |
          cd sentry
          python download.py ${{ github.event.inputs.version }}
          python build.py