name: Build Sentry

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to checkout and build to"
        required: true
        default: "0.5.0"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, windows-2022, ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        if: runner.os == 'macOS'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.22.2'

      - name: Build
        run: |
          python -m sentry.download ${{ github.event.inputs.version }}
          python -m sentry.build
      
      - name: Archive
        run: |
          zipname=$(python -m sentry.archive)
          echo "::set-output name=zipname::$zipname"
        shell: bash
        id: archive

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.archive.outputs.zipname }}
          path: ${{ steps.archive.outputs.zipname }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Prepare zips
        run: |
          mkdir zips
          mv ./*/*.zip ./zips

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: sentry-${{ github.event.inputs.version }}
          release_name: sentry-${{ github.event.inputs.version }}
          
      - name: Upload release assets
        uses: csexton/release-asset-action@v2
        with:
          pattern: "zips/*.zip"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}